# the expectation is that there are stage and prod environment buckets and the s3 bucket should be namespaced by
# environment, with the environment appended to the end of the bucket name, ie my-app-secrets-stage
s3Bucket: "my-app-secrets"
s3Key: "secrets.yaml"
